name: Lines Of Code

on: [push]

jobs:
  print-repo-url:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create Workspace Folder
      run: mkdir -p wrdir
    - name: get Lines Of Code repo
      run: git clone https://github.com/yasserbdj96/linesofcode.git wrdir
    - name: Install requirements
      run: pip install -r wrdir/requirements.txt
    - name: Get this repository badges 
      run: python wrdir/main.py --URL="https://github.com/${{ github.repository }}"
    - name: remove
      run: rm -rf wrdir
    #- name: Copy badges back to current repo     
    #  run: cp -R ./badges/. .
    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Add badges folder."
        git push