name: Run on MacOS
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v4
      - name: Install gettext
        run: |
          brew install gettext
          echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> $HOME/.bash_profile
          echo 'export LDFLAGS="-L/usr/local/opt/gettext/lib"' >> $HOME/.bash_profile
          echo 'export CPPFLAGS="-I/usr/local/opt/gettext/include"' >> $HOME/.bash_profile
          source $HOME/.bash_profile
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Create Workspace Folder
        run: mkdir -p wrdir && mkdir -p wrdir/hiphp
      - name: Copy Files & folders to Workspace Folder
        run: cp -r hiphp/* wrdir/hiphp && cp main.py wrdir/main.py
      - name: pip Upgrade
        run: python -m pip install --upgrade pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Test hiphp
        run: python wrdir/main.py
